# Generated by Django 2.2.6 on 2020-04-30 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_application', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScriptExecuteRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=100, verbose_name='业务名称')),
                ('username', models.CharField(max_length=50, verbose_name='执行用户名')),
                ('task_id', models.CharField(max_length=100, verbose_name='执行任务的id')),
                ('execute_time', models.TimeField(verbose_name='开始执行的时间')),
                ('machine_num', models.IntegerField(verbose_name='执行的ip数')),
                ('machine_ip', models.TextField(verbose_name='执行的ip信息')),
                ('state', models.CharField(max_length=20, verbose_name='任务的状态')),
                ('params', models.TextField(verbose_name='执行的参数')),
                ('result', models.TextField(verbose_name='执行详情')),
            ],
        ),
    ]
