# Generated by Django 2.2.6 on 2020-04-30 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_application', '0002_scriptexecuterecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scriptexecuterecord',
            name='execute_time',
            field=models.DateTimeField(verbose_name='开始执行的时间'),
        ),
    ]
