# Generated by Django 2.2.6 on 2020-08-25 16:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home_application', '0003_auto_20200430_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='scriptexecuterecord',
            name='create_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='任务下发时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scriptexecuterecord',
            name='end_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='执行结束时间'),
            preserve_default=False,
        ),
    ]
