# Generated by Django 2.2.6 on 2020-08-28 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_application', '0004_auto_20200825_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='scriptexecuterecord',
            name='script_id',
            field=models.CharField(default=1, max_length=100, verbose_name='执行脚本的id'),
            preserve_default=False,
        ),
    ]
